# Generated by Django 3.1.2 on 2020-10-31 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.TextField(verbose_name='Название')),
                ('street', models.TextField(verbose_name='Улица')),
                ('metro', models.TextField(verbose_name='Метро')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.TextField(verbose_name='Название')),
                ('finance', models.IntegerField(choices=[(0, 'Бесплатно'), (1, 'Платно')], verbose_name='Оплата')),
                ('schedule', models.IntegerField(choices=[(0, 'Общее'), (1, 'Индивидуальное')], verbose_name='Расписание')),
                ('duration', models.IntegerField(verbose_name='Длительность обучения')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Кружок',
                'verbose_name_plural': 'Кружки',
            },
        ),
    ]
