# Generated by Django 3.1.2 on 2020-10-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.TextField(verbose_name='Название')),
                ('status', models.TextField(verbose_name='Статус')),
                ('price', models.TextField(verbose_name='Стоимость')),
                ('type', models.TextField(verbose_name='Тип')),
                ('direction', models.TextField(verbose_name='Направленность')),
                ('start_date', models.TextField(verbose_name='Дата начала')),
                ('start_time', models.TextField(verbose_name='Время начала')),
                ('stop_date', models.TextField(verbose_name='Дата окончания')),
                ('stop_time', models.TextField(verbose_name='Время окончания')),
                ('online', models.BooleanField(verbose_name='Проводится онлайн')),
                ('place', models.TextField(verbose_name='Место проведения')),
                ('area', models.TextField(verbose_name='Район')),
                ('health_limitations', models.BooleanField(verbose_name='Доступно для лиц с ОВЗ')),
                ('censorship', models.TextField(verbose_name='Возрастной ценз')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
