# Generated by Django 3.1.2 on 2020-11-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201101_0417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.TextField(verbose_name='Название')),
                ('authior', models.TextField(verbose_name='Автор')),
                ('sity', models.TextField(verbose_name='Город')),
                ('publishing', models.TextField(verbose_name='Издательство')),
                ('year', models.TextField(verbose_name='Год')),
                ('description', models.TextField(verbose_name='Описание')),
                ('censorship', models.TextField(verbose_name='Возрастной ценз')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
